[package]
name = "engine-core"
version = "0.1.0"
edition = "2024"

[dependencies]
engine-cuda = { path = "../engine-cuda" }
engine-io = { path = "../engine-io" }
cudarc.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
flate2 = "1.0"

