[package]
name = "engine-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "titan"
path = "src/main.rs"

[dependencies]
engine-kvcache = { path = "../engine-kvcache" }
engine-core = { path = "../engine-core" }
engine-io = { path = "../engine-io" }
engine-cuda = { path = "../engine-cuda" }
cudarc.workspace = true
axum.workspace = true
tokio.workspace = true
tokio-macros.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
futures-core.workspace = true
futures-util.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
flate2 = "1.0"